### ISSUE TITLE
Tarea de Síntesis

### ISSUE THREAD

**Issue by MarcosJonathan17** [SistemasTecTlaxiaco/sintesis-MarcosJonathan17#2]
[SINTESIS.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-MarcosJonathan17/files/7150936/SINTESIS.pdf)

**Comment by JulioCesar69** [comment]
Muy bien elaborado.
Calificación: 100%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
